import { describe, expect, it } from 'vitest';
import mongoose from 'mongoose';
import Course from '../../src/models/Course.js';
import Question from '../../src/models/Question.js';
import Session from '../../src/models/Session.js';
import {
  createCourseQuestion,
  createCourseSession,
  defaultQuizWindow,
} from '../../src/services/aiCourseAuthoringTools.js';
import { listCourseSessions } from '../../src/services/aiCourseTools.js';

describe('AI course authoring tools', () => {
  it('rounds the default quiz start to the hour 24 hours ahead and ends it 12 hours later', () => {
    const window = defaultQuizWindow(new Date('2026-08-19T09:47:31.000Z'));
    expect(window.start.toISOString()).toBe('2026-08-20T09:00:00.000Z');
    expect(window.end.toISOString()).toBe('2026-08-20T21:00:00.000Z');
  });

  it('creates scheduled quizzes and generated questions with the required scope and tags', async (ctx) => {
    if (mongoose.connection.readyState !== 1) ctx.skip();
    const course = await Course.create({
      name: 'Mechanics', deptCode: 'PHYS', courseNumber: '123', section: '001', semester: 'Fall 2026',
      owner: 'prof-1', instructors: ['prof-1'], enrollmentCode: 'ABC123',
      tags: [{ value: 'kinematics', label: 'Kinematics' }],
    });
    const quizResult = await createCourseSession(course._id, 'prof-1', {
      name: 'AI Quiz', type: 'quiz', tags: ['Kinematics'],
    }, new Date('2026-08-19T09:47:31.000Z'));
    expect(quizResult.created).toBe(true);
    expect(quizResult.quiz_window).toEqual({ start: '2026-08-20T09:00:00.000Z', end: '2026-08-20T21:00:00.000Z' });

    const reusedQuiz = await createCourseSession(course._id, 'prof-1', {
      name: 'ai quiz', type: 'quiz',
    });
    expect(reusedQuiz).toMatchObject({
      created: false,
      session: { session_id: quizResult.session.session_id, name: 'AI Quiz' },
    });
    expect(await Session.countDocuments({ courseId: course._id, name: 'AI Quiz' })).toBe(1);
    expect((await listCourseSessions(course._id, { query: 'ai quiz' })).sessions).toEqual([
      expect.objectContaining({ session_id: quizResult.session.session_id, name: 'AI Quiz' }),
    ]);

    const libraryResult = await createCourseQuestion(course._id, 'prof-1', {
      type: 'short_answer', prompt: 'Define velocity.', tags: ['Kinematics'], points: 2,
    });
    expect(libraryResult.question).toMatchObject({ location: 'question_library', approved: false });
    expect(libraryResult.question.tags).toEqual(expect.arrayContaining(['Kinematics', 'Generated by AI']));

    const sessionResult = await createCourseQuestion(course._id, 'prof-1', {
      session_id: quizResult.session.session_id,
      type: 'multiple_choice',
      prompt: 'Which quantity is a vector?',
      options: [{ text: 'Speed', correct: false }, { text: 'Velocity', correct: true }],
      tags: [],
    });
    expect(sessionResult.question).toMatchObject({ location: 'session', approved: true });
    expect(sessionResult.question.tags).toEqual(expect.arrayContaining(['Kinematics', 'Generated by AI']));
    expect(sessionResult.warnings).toEqual([]);
    expect((await Session.findById(quizResult.session.session_id).lean()).questions).toContain(sessionResult.question.question_id);
    expect((await Question.findById(libraryResult.question.question_id).lean()).approved).toBe(false);
  });
});
