import { useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, List, ListItemButton, ListItemText } from '@mui/material';
import { useTranslation } from 'react-i18next';
import apiClient from '../../api/client';
import AiGradingForm from './AiGradingForm';
import { QUESTION_TYPES, normalizeQuestionType } from '../questions/constants';

function canManualGrade(question) { return ![QUESTION_TYPES.MULTIPLE_CHOICE, QUESTION_TYPES.TRUE_FALSE, QUESTION_TYPES.MULTI_SELECT, QUESTION_TYPES.NUMERICAL].includes(normalizeQuestionType(question)); }

export default function AiGradingModal({ open, onClose, courseId, sessionId, questions, needsGradingQuestionIds, onStarted }) {
  const { t } = useTranslation(); const [instructions, setInstructions] = useState([]); const [activeId, setActiveId] = useState(''); const [selected, setSelected] = useState([]); const [forms, setForms] = useState({}); const [error, setError] = useState(''); const [starting, setStarting] = useState(false);
  const manualQuestions = useMemo(() => questions.filter(canManualGrade), [questions]);
  useEffect(() => { if (!open) return; setSelected(manualQuestions.filter((q) => needsGradingQuestionIds.includes(String(q._id))).map((q) => String(q._id))); setActiveId(String(manualQuestions[0]?._id || '')); apiClient.get(`/ai/courses/${courseId}/grading-instructions`).then(({ data }) => setInstructions(data.instructions || [])).catch(() => setError(t('grades.aiGrading.failedLoad'))); }, [open, courseId, manualQuestions, needsGradingQuestionIds, t]);
  const saveInstruction = async (instruction) => { const { data } = await apiClient.post(`/ai/courses/${courseId}/grading-instructions`, instruction); setInstructions((current) => [...current.filter((entry) => entry._id !== data.instruction._id), data.instruction]); return data.instruction; };
  const deleteInstruction = async (instruction) => { await apiClient.delete(`/ai/courses/${courseId}/grading-instructions/${instruction._id}`); setInstructions((current) => current.filter((entry) => entry._id !== instruction._id)); setForms((current) => Object.fromEntries(Object.entries(current).map(([questionId, form]) => [questionId, form[`${instruction.kind}InstructionId`] === instruction._id ? { ...form, [`${instruction.kind}InstructionId`]: '', [instruction.kind]: '' } : form]))); };
  const start = async () => { setError(''); const missing = selected.filter((questionId) => !forms[questionId]?.gradingInstructionId); if (missing.length) { setError(t('grades.aiGrading.instructionsRequired')); setActiveId(missing[0]); return; } setStarting(true); try { const prepared = Object.fromEntries(selected.map((questionId) => { const form = forms[questionId] || {}; return [questionId, { grading: form.grading || '', feedback: form.feedback || '', regrade: !!form.regrade }]; })); const { data } = await apiClient.post(`/ai/courses/${courseId}/sessions/${sessionId}/ai-grading`, { questionIds: selected, instructions: prepared, regrade: Object.values(prepared).some((form) => form.regrade) }); onStarted(data.job); onClose(); } catch (err) { setError(err.response?.data?.message || t('grades.aiGrading.failedStart')); } finally { setStarting(false); } };
  const form = forms[activeId] || {}; return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md"><DialogTitle>{t('grades.aiGrading.title')}</DialogTitle><DialogContent dividers>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: '150px 1fr' }, gap: 2 }}><List dense sx={{ borderRight: { sm: 1 }, borderColor: 'divider', maxHeight: 440, overflowY: 'auto' }}>{questions.map((question, index) => { const id = String(question._id); const enabled = canManualGrade(question); return <ListItemButton key={id} disabled={!enabled} selected={activeId === id} onClick={() => setActiveId(id)}><Checkbox size="small" checked={selected.includes(id)} disabled={!enabled} onClick={(event) => { event.stopPropagation(); setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }} /><ListItemText primary={`Q${index + 1}`} /></ListItemButton>; })}</List><AiGradingForm key={activeId} value={form} instructions={instructions} onChange={(value) => setForms((current) => ({ ...current, [activeId]: value }))} onSaveInstruction={saveInstruction} onDeleteInstruction={deleteInstruction} /></Box></DialogContent><DialogActions><Button onClick={onClose}>{t('common.cancel')}</Button><Button variant="contained" disabled={!selected.length || starting} onClick={start}>{t('grades.aiGrading.start')}</Button></DialogActions></Dialog>;
}
