import Course from '../models/Course.js';
import Question from '../models/Question.js';
import Response from '../models/Response.js';
import Session from '../models/Session.js';
import { getNormalizedTagValue, mergeNormalizedTags, normalizeTags } from './questionImportExport.js';
import { inheritSessionTagsForQuestions } from './sessionQuestionTags.js';
import { buildSessionResponseTracking } from '../utils/sessionResponseTracking.js';

const AI_GENERATED_TAG = { value: 'Generated by AI', label: 'Generated by AI' };
const QUESTION_TYPES = {
  multiple_choice: 0,
  true_false: 1,
  short_answer: 2,
  multiple_select: 3,
  numerical: 4,
  slide: 6,
};
const QUESTION_TYPE_NAMES = Object.fromEntries(Object.entries(QUESTION_TYPES).map(([name, value]) => [value, name]));

function normalizeDate(value, fieldName) {
  const date = value ? new Date(value) : null;
  if (!date || Number.isNaN(date.getTime())) throw new Error(`${fieldName} must be a valid date and time`);
  return date;
}

export function defaultQuizWindow(now = new Date()) {
  const start = new Date(now.getTime() + 24 * 60 * 60 * 1000);
  start.setMinutes(0, 0, 0);
  const end = new Date(start.getTime() + 12 * 60 * 60 * 1000);
  return { start, end };
}

function resolveQuizWindow({ quizStart, quizEnd }, now = new Date()) {
  const defaults = defaultQuizWindow(now);
  const start = quizStart ? normalizeDate(quizStart, 'quiz_start') : defaults.start;
  const end = quizEnd ? normalizeDate(quizEnd, 'quiz_end') : new Date(start.getTime() + 12 * 60 * 60 * 1000);
  if (end <= start) throw new Error('quiz_end must be after quiz_start');
  return { start, end };
}

function courseTagMap(course) {
  const tags = normalizeTags(course?.tags || []);
  const map = new Map();
  tags.forEach((tag) => {
    map.set(getNormalizedTagValue(tag), tag);
    map.set(String(tag.label || '').trim().toLowerCase(), tag);
  });
  return map;
}

function resolveCourseTags(course, requestedTags = []) {
  const tagsByName = courseTagMap(course);
  const resolved = [];
  const unknown = [];
  [...new Set((requestedTags || []).map((tag) => String(tag || '').trim()).filter(Boolean))].forEach((requestedTag) => {
    const tag = tagsByName.get(requestedTag.toLowerCase());
    if (tag) resolved.push(tag);
    else unknown.push(requestedTag);
  });
  return { resolved: mergeNormalizedTags(resolved), unknown };
}

function topicWarnings(course, resolvedTags, unknownTags) {
  const warnings = [];
  if (unknownTags.length > 0) warnings.push(`These requested course topics were not configured and were not added: ${unknownTags.join(', ')}.`);
  if ((course?.tags || []).length === 0) warnings.push('This course has no course topics configured, so no topic tag could be selected.');
  else if (resolvedTags.length === 0) warnings.push('No course topic could be determined for this question.');
  return warnings;
}

async function requireCourse(courseId) {
  const course = await Course.findById(String(courseId)).lean();
  if (!course) throw new Error('Course not found');
  return course;
}

async function requireSession(courseId, sessionId) {
  const session = await Session.findOne({ _id: String(sessionId), courseId: String(courseId), studentCreated: { $ne: true } }).lean();
  if (!session) throw new Error('Session not found in this course');
  return session;
}

function buildOptions(type, options = [], correctAnswer = undefined) {
  if (type === QUESTION_TYPES.true_false) {
    const normalizedAnswer = String(correctAnswer).trim().toLowerCase();
    if (!['true', 'false'].includes(normalizedAnswer)) throw new Error('correct_answer must be true or false for a true/false question');
    return ['True', 'False'].map((text) => ({ answer: text, content: text, plainText: text, correct: text.toLowerCase() === normalizedAnswer }));
  }
  if (![QUESTION_TYPES.multiple_choice, QUESTION_TYPES.multiple_select].includes(type)) return [];
  if (!Array.isArray(options) || options.length < 2) throw new Error('Multiple-choice questions require at least two options');
  const normalized = options.map((option) => {
    const text = String(option?.text || '').trim();
    if (!text) throw new Error('Every question option requires text');
    return { answer: text, content: text, plainText: text, correct: !!option.correct };
  });
  const correctCount = normalized.filter((option) => option.correct).length;
  if (type === QUESTION_TYPES.multiple_choice && correctCount !== 1) throw new Error('A multiple-choice question requires exactly one correct option');
  if (type === QUESTION_TYPES.multiple_select && correctCount < 1) throw new Error('A multiple-select question requires at least one correct option');
  return normalized;
}

function serializeSession(session) {
  return {
    session_id: String(session._id),
    name: session.name,
    description: session.description || '',
    type: session.quiz ? 'quiz' : 'interactive',
    status: session.status,
    quiz_start: session.quizStart || null,
    quiz_end: session.quizEnd || null,
    tags: normalizeTags(session.tags || []).map((tag) => tag.label),
  };
}

function serializeAuthoredQuestion(question, warnings = []) {
  return {
    question_id: String(question._id),
    session_id: String(question.sessionId || ''),
    location: question.sessionId ? 'session' : 'question_library',
    type: QUESTION_TYPE_NAMES[question.type] || String(question.type),
    prompt: question.plainText || question.content || '',
    approved: !!question.approved,
    tags: normalizeTags(question.tags || []).map((tag) => tag.label),
    warnings,
  };
}

export async function createCourseSession(courseId, userId, input, now = new Date()) {
  const course = await requireCourse(courseId);
  const type = input.type === 'quiz' ? 'quiz' : 'interactive';
  const name = String(input.name || '').trim();
  if (!name) throw new Error('Session name is required');
  const { resolved, unknown } = resolveCourseTags(course, input.tags);
  const warnings = unknown.length ? [`These requested course topics were not configured and were not added: ${unknown.join(', ')}.`] : [];
  const quizWindow = type === 'quiz' ? resolveQuizWindow({ quizStart: input.quiz_start, quizEnd: input.quiz_end }, now) : null;
  const session = await Session.create({
    name,
    description: String(input.description || '').trim(),
    courseId: String(course._id),
    creator: String(userId),
    status: 'hidden',
    quiz: type === 'quiz',
    practiceQuiz: false,
    quizStart: quizWindow?.start,
    quizEnd: quizWindow?.end,
    tags: resolved,
    hasResponses: false,
    questionResponseCounts: {},
    richTextChatEnabled: true,
  });
  await Course.findByIdAndUpdate(course._id, { $addToSet: { sessions: session._id } });
  return {
    session: serializeSession(session),
    warnings,
    ...(quizWindow ? { quiz_window: { start: quizWindow.start.toISOString(), end: quizWindow.end.toISOString() } } : {}),
  };
}

export async function editCourseSession(courseId, sessionId, input, now = new Date()) {
  const [course, session] = await Promise.all([requireCourse(courseId), requireSession(courseId, sessionId)]);
  const updates = {};
  if (input.name !== undefined) updates.name = String(input.name || '').trim();
  if (input.description !== undefined) updates.description = String(input.description || '').trim();
  if (input.tags !== undefined) {
    const { resolved, unknown } = resolveCourseTags(course, input.tags);
    updates.tags = resolved;
    updates.tagWarnings = unknown.length ? [`These requested course topics were not configured and were not added: ${unknown.join(', ')}.`] : [];
  }
  const nextType = input.type || (session.quiz ? 'quiz' : 'interactive');
  let quizWindow = null;
  if (input.type !== undefined || input.quiz_start !== undefined || input.quiz_end !== undefined) {
    updates.quiz = nextType === 'quiz';
    updates.practiceQuiz = false;
    if (updates.quiz) {
      quizWindow = resolveQuizWindow({
        quizStart: input.quiz_start || session.quizStart,
        quizEnd: input.quiz_end || (input.quiz_start ? undefined : session.quizEnd),
      }, now);
      updates.quizStart = quizWindow.start;
      updates.quizEnd = quizWindow.end;
    } else {
      updates.quizStart = null;
      updates.quizEnd = null;
    }
  }
  const warnings = updates.tagWarnings || [];
  delete updates.tagWarnings;
  if (Object.keys(updates).length === 0) throw new Error('Provide at least one session field to edit');
  const updated = await Session.findByIdAndUpdate(session._id, { $set: updates }, { returnDocument: 'after' });
  if (updates.tags !== undefined) await inheritSessionTagsForQuestions(updated.toObject());
  return {
    session: serializeSession(updated),
    warnings,
    ...(quizWindow ? { quiz_window: { start: quizWindow.start.toISOString(), end: quizWindow.end.toISOString() } } : {}),
  };
}

export async function listCourseQuestions(courseId, { query = '', offset = 0, limit = 25, location = 'all' } = {}) {
  await requireCourse(courseId);
  const filter = { courseId: String(courseId) };
  if (location === 'library') filter.sessionId = '';
  if (location === 'session') filter.sessionId = { $ne: '' };
  if (query) filter.$or = [
    { plainText: { $regex: String(query), $options: 'i' } },
    { content: { $regex: String(query), $options: 'i' } },
  ];
  const boundedOffset = Math.max(0, Number(offset) || 0);
  const boundedLimit = Math.max(1, Math.min(50, Number(limit) || 25));
  const [total, questions] = await Promise.all([
    Question.countDocuments(filter),
    Question.find(filter).sort({ createdAt: -1 }).skip(boundedOffset).limit(boundedLimit).lean(),
  ]);
  return {
    question_count: total,
    offset: boundedOffset,
    returned_count: questions.length,
    next_offset: boundedOffset + questions.length < total ? boundedOffset + questions.length : null,
    questions: questions.map((question) => serializeAuthoredQuestion(question)),
  };
}

export async function createCourseQuestion(courseId, userId, input) {
  const course = await requireCourse(courseId);
  const session = input.session_id ? await requireSession(courseId, input.session_id) : null;
  const type = QUESTION_TYPES[input.type];
  if (type === undefined) throw new Error('Unsupported question type');
  const prompt = String(input.prompt || '').trim();
  if (!prompt) throw new Error('Question prompt is required');
  const options = buildOptions(type, input.options, input.correct_answer);
  const { resolved, unknown } = resolveCourseTags(course, input.tags);
  const topicTags = mergeNormalizedTags(resolved, session?.tags || []);
  const warnings = topicWarnings(course, topicTags, unknown);
  const tags = mergeNormalizedTags(topicTags, [AI_GENERATED_TAG]);
  const correctNumerical = Number(input.correct_numerical);
  if (type === QUESTION_TYPES.numerical && !Number.isFinite(correctNumerical)) throw new Error('correct_numerical is required for a numerical question');
  const question = await Question.create({
    type,
    content: prompt,
    plainText: prompt,
    options,
    ...(type === QUESTION_TYPES.numerical ? {
      correctNumerical,
      toleranceNumerical: Number(input.tolerance_numerical || 0),
    } : {}),
    creator: String(userId),
    owner: String(userId),
    sessionId: session ? String(session._id) : '',
    courseId: String(course._id),
    originalCourse: String(course._id),
    solution: String(input.solution || ''),
    solution_plainText: String(input.solution || ''),
    sessionOptions: { points: Math.max(0, Number(input.points ?? 1)), hidden: true, stats: false, correct: false, attempts: [] },
    tags,
    approved: !!session,
    studentCreated: false,
  });
  if (session) {
    const questionIds = [...new Set([...(session.questions || []).map(String), String(question._id)])];
    const tracking = buildSessionResponseTracking(questionIds, session.questionResponseCounts);
    await Session.findByIdAndUpdate(session._id, { $set: { questions: questionIds, hasResponses: tracking.hasResponses, questionResponseCounts: tracking.questionResponseCounts } });
  }
  return { question: serializeAuthoredQuestion(question, warnings), warnings };
}

export async function editCourseQuestion(courseId, questionId, input) {
  const [course, question] = await Promise.all([
    requireCourse(courseId),
    Question.findOne({ _id: String(questionId), courseId: String(courseId) }),
  ]);
  if (!question) throw new Error('Question not found in this course');
  const session = question.sessionId ? await requireSession(courseId, question.sessionId) : null;
  const updates = {};
  if (input.prompt !== undefined) {
    updates.content = String(input.prompt || '').trim();
    updates.plainText = updates.content;
  }
  if (input.solution !== undefined) {
    updates.solution = String(input.solution || '');
    updates.solution_plainText = updates.solution;
  }
  if (input.points !== undefined) updates['sessionOptions.points'] = Math.max(0, Number(input.points));
  const nextType = input.type !== undefined ? QUESTION_TYPES[input.type] : question.type;
  if (nextType === undefined) throw new Error('Unsupported question type');
  const hasResponses = await Response.exists({ questionId: String(question._id) });
  if (nextType !== question.type && hasResponses) throw new Error('Question type cannot be changed because it has response data');
  if (input.type !== undefined) updates.type = nextType;
  if (input.options !== undefined || input.correct_answer !== undefined || input.type !== undefined) {
    const nextOptions = buildOptions(nextType, input.options ?? question.options.map((option) => ({ text: option.plainText || option.answer, correct: option.correct })), input.correct_answer);
    if (hasResponses && nextOptions.length !== question.options.length) throw new Error('Question options cannot be added or removed because it has response data');
    updates.options = nextOptions;
  }
  if (nextType === QUESTION_TYPES.numerical) {
    if (input.correct_numerical !== undefined) updates.correctNumerical = Number(input.correct_numerical);
    if (input.tolerance_numerical !== undefined) updates.toleranceNumerical = Number(input.tolerance_numerical);
  }
  const tagSelection = input.tags !== undefined ? resolveCourseTags(course, input.tags) : null;
  const existingCourseTags = normalizeTags(question.tags).filter((tag) => courseTagMap(course).has(getNormalizedTagValue(tag)));
  const resolvedTags = mergeNormalizedTags(tagSelection?.resolved || existingCourseTags, session?.tags || []);
  const warnings = topicWarnings(course, resolvedTags, tagSelection?.unknown || []);
  updates.tags = mergeNormalizedTags(resolvedTags, [AI_GENERATED_TAG]);
  updates.approved = !!session;
  updates.lastEditedAt = new Date();
  const updated = await Question.findByIdAndUpdate(question._id, { $set: updates }, { returnDocument: 'after' });
  return { question: serializeAuthoredQuestion(updated, warnings), warnings };
}
